### ISSUE TITLE
Integrate Google Font Loading for Books

### ISSUE THREAD

**Issue by VarunS1997** [Project-Hedron/Issues-and-Tasks#131]
It would be cool (and well-liked) if we could allow users to have books use custom fonts backed by Google Fonts.

Preliminary research suggests this is possible and not _too_ hard. 

And it would be pretty fantastic.

**Comment by HLMelton** [comment]
100% agree and google has a ton to start with so it would lend a good amount to customization of individuals rulebooks and give context to "oh this is a Sci-Fi game" or vice versa for a fantasy themed one. 

Would we ever consider letting people import their own fonts into their books if they have? For example, if they have a .otf/.ttf file they can upload into their rulebook.

**Comment by VarunS1997** [comment]
Yeah that would be a good thing to do eventually -- I made #133 just now for that. 

I think though that starting with just the ability to customize the font with google fonts would be like exceptional. It would let people pick from Google's hundreds of thousands of fonts. 

The OTF/TTF would be a cool extra feature, but probably a bit niche. Not everyone has those files generally.

**Comment by VarunS1997** [comment]
This is now supported on a book-level. More fine-grained control would probably be appreciated in the future.
