### ISSUE TITLE
Character Sheet Editor Freezes and Won't Re-Open

### ISSUE THREAD

**Issue by VarunS1997** [Project-Hedron/Issues-and-Tasks#145]
Discord or RG username: VariSami
Name of the game: - (unnamed template)
Description:

I was editing a new template together without it being associated with a game yet. It had no elements in any of the tabs and I had added a second tab that I tried to name 'Characters'. The editor crashed and refuses to open even after a hard reset.
Steps to reproduce:
- ???

Platform: Browser (Chrome)

Any additional relevant info: Console log for trying to open the character sheet editor again attached.

**Comment by VarunS1997** [comment]
![image](https://github.com/user-attachments/assets/dae60616-051b-4812-8aac-2f1248609aeb)

**Comment by SirClutch6** [comment]
During duplication:

Editor did not crash when creating a new tab and naming it, as stated above. The problem occurred when deleting a tab. The editor does then crash, and the site refuses to show the `Character sheet templates` page at all, even after refreshing. Continuing to investigate.

**Comment by SirClutch6** [comment]
Update: Any time you are viewing any template and refresh the page, the entire template system crashes. It appears that all templates are viewed/edited by use of the id in a route param, and refreshing the page causes the route param to revert to "undefined".

**Comment by VarunS1997** [comment]
It's possible that this refresh issue actually causes several other issues as well, so fixing it would definitely be important. Maybe we can just wait on real route params? Or something like that? Not sure, leaving it to your discretion.

**Comment by darrow97** [comment]
There is an existing function in the project called `ensureBackScreen` that can be added to a `Stack.Navigator` and guarantee the back arrow that sometimes appears in the header area has a target destination. I added this function to the `CharacterSheetStack`.

The url issue is still to be resolved, but now the user has the ability to get back to the Browse Templates page, which will properly populate the site state and allow the user to get back to the desired template and continue editing the template

**Comment by darrow97** [comment]
closed with Tabletop-Mirror/Role-Gate-Frontend#4
