### ISSUE TITLE
Add Functionality to Search Game Text

### ISSUE THREAD

**Issue by VarunS1997** [Project-Hedron/Issues-and-Tasks#154]
It appears there's no way to search the game text, but there really should be... At least fetch the last X results or something.

It's not like our API calls are super efficient anyway.

**Comment by darrow97** [comment]
@VarunS1997 what do you mean by game text? Is that only the messages that appear on the game page?

**Comment by VarunS1997** [comment]
Specifically, I mean the user messages. So like when you say or describe something, and if possible, the roll+ messages.

In this example screenshot, it should search all of the "tes", "test", "tes", "wow" messages in blue. As well as the white "test" and "was" messages.

Knowing our DB, this might be intensive, so expect to create a spinning icon while the search query is run. We could also limit it to like first 10-20 results.

![image](https://github.com/user-attachments/assets/ae97b94b-0e65-4424-9a72-fb09cfb1487d)

**Comment by darrow97** [comment]
The search bar functionality resides in the Searchbar component on the Frontend and does not involve the Backend.

**Comment by darrow97** [comment]
This needs:
- [ ] a search endpoint on the BE
- [ ] a search component that uses the new BE endpoint

Varun suggests a using the SELECT query for reading messages as a reference point and that it could be as simple as performing a LIKE operation on the right table.

**Comment by VarunS1997** [comment]
You'll also need a WHERE clause to make sure you don't search _all_ messages across _all_ games.

**Comment by darrow97** [comment]
@VarunS1997 do you want the rest of the search bar functionality to start hitting the backend or leave it as it is for now?

**Comment by VarunS1997** [comment]
Hmm? Feel free to start branches and push code to both backend and front end. I won't deploy until we're finishing up the whole sprint

**Comment by darrow97** [comment]
Sorry, to clarify my question: do you want the existing searchbar functionality to change to hitting the backend

**Comment by darrow97** [comment]
My plan is to create a new search bar component that will be easy to tie into from any page.
This component will be a modal that only requires the user to input text. The results will then be grouped by where the result comes from (ie game name, lines from the game text, etc)

This should be easy to expand upon and add functionality over time as well

**Comment by VarunS1997** [comment]
Whatever is easier. I think it's probably easier to expand the search bar functionality than to change how it works from the ground up.

We are, unfortunately, in a move fast and break what's already broken mode of operation. :)

**Comment by darrow97** [comment]
true. then maybe for now i'll add a flag to the existing search bar so that it knows to hit the BE rather than filter on what data is already present on the FE

**Comment by darrow97** [comment]
created ticket #161 to handle the backend portion of the search bar

**Comment by darrow97** [comment]
closed with Tabletop-Mirror/Role-Gate-Frontend#3
