### ISSUE TITLE
Unlock Macros for All Users

### ISSUE THREAD

**Issue by VarunS1997** [Project-Hedron/Issues-and-Tasks#155]
This is a bit of a question/toss-up. 

This is the main feature that seperates Copper and Silver tier. 

If we make this, there's a non-zero chance that it would hurt our revenue...

BUT, it would definitely be a feature people notice!

**Comment by VarunS1997** [comment]
For reference, there's 139 people with Silver. 
This means they are about $695/month of revenue

**Comment by VarunS1997** [comment]
Correction: I believe this is actually asserting that ONLY tiered users can use macros. If that's correct -- we should definitely fix this. And leave creation of Macros to Silver+.

**Comment by darrow97** [comment]
completed by @VarunS1997 in the update CUSTOM TONES. MACROS FOR ALL
