### ISSUE TITLE
The Map Maker Needs Work

### ISSUE THREAD

**Issue by VarunS1997** [Project-Hedron/Issues-and-Tasks#19]
In short, everyone (including me) recognizes that the Map Maker needs improvements. 

It just doesn't have an intuitive logic or layout. Even though the logic makes sense from a tech perspective, it doesn't make sense for users. 

And even then, it may still not make sense from a tech perspective... Specifically, maybe Geography and Regions should be merged together? Or maybe Geography should be more focused on terrain?

Not to mention the code... 😬

**Comment by HLMelton** [comment]
Do we still need this issue since its been updated to the new SVG tooling?

**Comment by VarunS1997** [comment]
I think overall, this is complete. I mean there might be more work to do, but we can spin-off a separate re-evaluation.
