### ISSUE TITLE
Add Description of "Default Dice" to Rule System Editor

### ISSUE THREAD

**Issue by VarunS1997** [Project-Hedron/Issues-and-Tasks#199]
The Rule System Editor uses default dice, but it's not clear what it does, please attach this explanation:

"Default Dice are used to specify the initial dice configuration when a new check is created. These can be overridden and are purely for convenience."

While we're at it, let's rename the section to "Default Dice Configuration", rather than "Your Default Dice".

**Comment by MatthewRVT** [comment]
PR reviewed by Varun and approved

**Comment by VarunS1997** [comment]
Note: Specifically, this change was added to 2024.09.02
