### ISSUE TITLE
On Pages that Use Templates, Include the Template Name

### ISSUE THREAD

**Issue by VarunS1997** [Project-Hedron/Issues-and-Tasks#211]
When pages use a template that the user defined, it would be valuable to include in the page subtitle what the templates name is.

For example, "The Final Flame Universe" has a template called "Places", so it would be good if instead of:
```
Part of the Book: The Final Flame Universe
```
we show:
```
Books > The Final Flame Universe > Places
```

And of course, "Books", "The Final Flame Universe" should both be links.
Later on, we can even add #210 to hyperlink "Places" in this example.

If a page doesn't use a template, then it shouldn't show the last > and "Places".

**Comment by MatthewRVT** [comment]
I think I have it completely implemented on my branch template_navigation but will need to do more testing as I can't see the templates on any book I myself haven't made. This may be due to my code being incomplete or me only having access to books that have no template generated pages.

**Comment by MatthewRVT** [comment]
PR approved and merged
