### ISSUE TITLE
Add an indicator of what page you're currently on when you can scroll pages

### ISSUE THREAD

**Issue by MatthewRVT** [Project-Hedron/Issues-and-Tasks#223]
Honestly its a bit of a pain to figure out what page I'm on by figuring out the number between the labels on the left and right page buttons.
Would have to change the list, table, and grid layout components to display what page you're currently on

example: DnD 5E items tab has arrows you can scroll left and right on and when I'm on page 3 the left arrow says page 2 of 9 and the right one says page 4 of 9 with no indicator that I'm on page 3.

**Comment by VarunS1997** [comment]
This is actually a UX thing -- it should actually go directly to UX folks. Closing this bug as I forwarded it to them directly.
